// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sibers.leage.domain;

import com.sibers.leage.domain.Player;
import com.sibers.leage.domain.Team;
import com.sibers.leage.domain.TeamDataOnDemand;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PlayerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlayerDataOnDemand: @Component;
    
    private Random PlayerDataOnDemand.rnd = new SecureRandom();
    
    private List<Player> PlayerDataOnDemand.data;
    
    @Autowired
    private TeamDataOnDemand PlayerDataOnDemand.teamDataOnDemand;
    
    public Player PlayerDataOnDemand.getNewTransientPlayer(int index) {
        Player obj = new Player();
        setFirstName(obj, index);
        setHeight(obj, index);
        setKickingAccuracy(obj, index);
        setKickingPower(obj, index);
        setLastName(obj, index);
        setSpeed(obj, index);
        setTeam(obj, index);
        setWeight(obj, index);
        return obj;
    }
    
    public void PlayerDataOnDemand.setFirstName(Player obj, int index) {
        String firstName = "firstName_" + index;
        if (firstName.length() > 50) {
            firstName = firstName.substring(0, 50);
        }
        obj.setFirstName(firstName);
    }
    
    public void PlayerDataOnDemand.setHeight(Player obj, int index) {
        int height = index;
        if (height < 1) {
            height = 1;
        }
        obj.setHeight(height);
    }
    
    public void PlayerDataOnDemand.setKickingAccuracy(Player obj, int index) {
        int kickingAccuracy = index;
        if (kickingAccuracy < 1 || kickingAccuracy > 10) {
            kickingAccuracy = 10;
        }
        obj.setKickingAccuracy(kickingAccuracy);
    }
    
    public void PlayerDataOnDemand.setKickingPower(Player obj, int index) {
        int kickingPower = index;
        if (kickingPower < 1 || kickingPower > 10) {
            kickingPower = 10;
        }
        obj.setKickingPower(kickingPower);
    }
    
    public void PlayerDataOnDemand.setLastName(Player obj, int index) {
        String lastName = "lastName_" + index;
        if (lastName.length() > 50) {
            lastName = lastName.substring(0, 50);
        }
        obj.setLastName(lastName);
    }
    
    public void PlayerDataOnDemand.setSpeed(Player obj, int index) {
        int speed = index;
        if (speed < 1 || speed > 10) {
            speed = 10;
        }
        obj.setSpeed(speed);
    }
    
    public void PlayerDataOnDemand.setTeam(Player obj, int index) {
        Team team = teamDataOnDemand.getRandomTeam();
        obj.setTeam(team);
    }
    
    public void PlayerDataOnDemand.setWeight(Player obj, int index) {
        int weight = index;
        if (weight < 1) {
            weight = 1;
        }
        obj.setWeight(weight);
    }
    
    public Player PlayerDataOnDemand.getSpecificPlayer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Player obj = data.get(index);
        return Player.findPlayer(obj.getId());
    }
    
    public Player PlayerDataOnDemand.getRandomPlayer() {
        init();
        Player obj = data.get(rnd.nextInt(data.size()));
        return Player.findPlayer(obj.getId());
    }
    
    public boolean PlayerDataOnDemand.modifyPlayer(Player obj) {
        return false;
    }
    
    public void PlayerDataOnDemand.init() {
        data = Player.findPlayerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Player' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sibers.leage.domain.Player>();
        for (int i = 0; i < 10; i++) {
            Player obj = getNewTransientPlayer(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
